### ISSUE TITLE
Long variable name

### ISSUE THREAD

**Issue by pi-kappa-devel** [pi-kappa-devel/diseq#16]
Give `use_heteroscedasticity_consistent_errors` variable in `estimate`  method a shorter name.

**Comment by Doktor-Doom** [comment]
I had to look up the term and found it spelled with a k interchangeably, have you considered keeping a guide of variable names in a separate markdown file and using key...

use_hs_errors = use_heteroscedasticity_consistent_errors or, 

use_Heterosked_errors or a variation of this?
heterosked/heterosced might be easier to remember

I'm not familiar with C++ syntax rules, so I can't tell you if its okay to use capital letters.

**Comment by pi-kappa-devel** [comment]
> use_hs_errors = use_heteroscedasticity_consistent_errors or,

This can work! Also `use_heteroscedastic_errors` is an expressive alternative that stays under 30 characters.

> use_Heterosked_errors or a variation of this?
> heterosked/heterosced might be easier to remember
>
> I'm not familiar with C++ syntax rules, so I can't tell you if its okay to use capital letters.

It is perfectly valid to have capital letters in C++. The `estimate` method is implemented `R`, for which is also valid to have capital letters. The linter setup for the package uses snake case style though, so your first suggestion is compatible with the styling rules.

**Comment by pi-kappa-devel** [comment]
Shorten the variable name to `use_heteroscedastic_errors`.
